name: audiofileplayer
description: A Flutter plugin for audio playback.
version: 2.1.1
homepage: https://github.com/google/flutter.plugins/tree/master/packages/audiofileplayer

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.0.0
  meta: ^1.9.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.google.flutter.plugins.audiofileplayer
        pluginClass: AudiofileplayerPlugin
      ios:
        pluginClass: AudiofileplayerPlugin
